import { LazyCanvas, Outline, CircleLayer, ImageLayer, EllipseImageLayer, SquareLayer, EllipseLayer, NgonLayer, RectangleLayer, TextLayer, Font, saveFile } from "../src";

let lazy = new LazyCanvas()
    .createNewCanvas(645, 1100)
    .addLayers(
        new RectangleLayer()
            .setX(0)
            .setY(0)
            .setWidth(645)
            .setHeight(1100)
            .setColor('#000')
            .setCentering('legacy'),
        new ImageLayer()
            .setX(107.5)
            .setY(75)
            .setWidth(100)
            .setHeight(100)
            .setImage('https://i.pinimg.com/1200x/f3/32/19/f332192b2090f437ca9f49c1002287b6.jpg')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new CircleLayer()
            .setX(107.5)
            .setY(200)
            .setRadius(50)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new EllipseLayer()
            .setX(107.5)
            .setY(325)
            .setWidth(130)
            .setHeight(100)
            .setRadius(50)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new EllipseImageLayer()
            .setX(107.5)
            .setY(450)
            .setWidth(100)
            .setHeight(100)
            .setRadius(50)
            .setImage('https://i.pinimg.com/1200x/f3/32/19/f332192b2090f437ca9f49c1002287b6.jpg')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new SquareLayer()
            .setX(107.5)
            .setY(575)
            .setWidth(100)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new RectangleLayer()
            .setX(107.5)
            .setY(700)
            .setWidth(130)
            .setHeight(100)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new NgonLayer()
            .setX(107.5)
            .setY(825)
            .setRadius(50)
            .setSides(6)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            ),
        new TextLayer()
            .setX(107.5)
            .setAlign('center')
            .setY(950)
            .setText('Test for Outline')
            .setFont('JoeKubert')
            .setFontSize(20)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(1)
                ),
        new ImageLayer()
            .setX(322.5)
            .setY(75)
            .setWidth(100)
            .setHeight(100)
            .setImage('https://i.pinimg.com/1200x/f3/32/19/f332192b2090f437ca9f49c1002287b6.jpg')
            .setOutline(
                new Outline()
                    .setType('outer')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new CircleLayer()
            .setX(322.5)
            .setY(200)
            .setRadius(50)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new EllipseLayer()
            .setX(322.5)
            .setY(325)
            .setWidth(130)
            .setHeight(100)
            .setRadius(50)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new EllipseImageLayer()
            .setX(322.5)
            .setY(450)
            .setWidth(100)
            .setHeight(100)
            .setRadius(50)
            .setImage('https://i.pinimg.com/1200x/f3/32/19/f332192b2090f437ca9f49c1002287b6.jpg')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new SquareLayer()
            .setX(322.5)
            .setY(575)
            .setWidth(100)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new RectangleLayer()
            .setX(322.5)
            .setY(700)
            .setWidth(130)
            .setHeight(100)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new NgonLayer()
            .setX(322.5)
            .setY(825)
            .setRadius(50)
            .setSides(6)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            ),
        new TextLayer()
            .setX(322.5)
            .setAlign('center')
            .setY(950)
            .setText('Test for Outline')
            .setFont('JoeKubert')
            .setFontSize(20)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('center')
                    .setColor('#ff8a8a')
                    .setStroke(1)
                ),
        new ImageLayer()
            .setX(537.5)
            .setY(75)
            .setWidth(100)
            .setHeight(100)
            .setImage('https://i.pinimg.com/1200x/f3/32/19/f332192b2090f437ca9f49c1002287b6.jpg')
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new CircleLayer()
            .setX(537.5)
            .setY(200)
            .setRadius(50)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new EllipseLayer()
            .setX(537.5)
            .setY(325)
            .setWidth(130)
            .setHeight(100)
            .setRadius(50)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new EllipseImageLayer()
            .setX(537.5)
            .setY(450)
            .setWidth(100)
            .setHeight(100)
            .setRadius(50)
            .setImage('https://i.pinimg.com/1200x/f3/32/19/f332192b2090f437ca9f49c1002287b6.jpg')
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new SquareLayer()
            .setX(537.5)
            .setY(575)
            .setWidth(100)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new RectangleLayer()
            .setX(537.5)
            .setY(700)
            .setWidth(130)
            .setHeight(100)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            )
            .setCentering('legacy'),
        new NgonLayer()
            .setX(537.5)
            .setY(825)
            .setRadius(50)
            .setSides(6)
            .setColor('#fff')
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(8)
            ),
        new TextLayer()
            .setX(537.5)
            .setAlign('center')
            .setY(950)
            .setText('Test for Outline Test for Outline')
            .setFont('JoeKubert')
            .setFontSize(20)
            .setColor('#fff')
            .setWidth(200)
            .setHeight(50)
            .setMultiline(true)
            .setOutline(
                new Outline()
                    .setType('inner')
                    .setColor('#ff8a8a')
                    .setStroke(1)
                ),
    ).loadFonts(
        new Font()
            .setFamily("JoeKubert")
            .setWeight("regular")
            .setPath("./fonts/v_CCJoeKubert-Doubled_v1.3.ttf")
    )

async function main() {
    let data = await lazy.renderImage()
    console.log(data)
    await saveFile(data, 'png', 'output')
}

main()